DmlDemo.dmlUpdateMultiple_right1();
DmlDemo.dmlInsertMultiple_right2();
DmlDemo.dmlInsertMultiple_right();


DmlDemo.dmlInsertDemo_stndObj();
DmlDemo.dmlInsertDemo_cstmObj();
DmlDemo.dmlUpdateDemo_1();
DmlDemo.dmlUpdateDemo_3();
DmlDemo.dmlInsertDemo_4();
DmlDemo.dmlInsertDemo_5();
//DmlDemo.dmlInsertMultiple_wrong();

//list<acount> delAcc = [select id from accunt where name like '%B.0$'];
//delete [select id from accunt where createdDate = THIS_WEEK];

